# Generated by Django 4.1.5 on 2023-03-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='productImages')),
                ('product_price', models.IntegerField()),
                ('product_desc', models.CharField(max_length=300)),
                ('product_rating', models.IntegerField()),
            ],
        ),
    ]
