# Generated by Django 4.1.5 on 2023-03-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='product_title',
            field=models.CharField(default='mobile', max_length=50),
        ),
    ]
