# Generated by Django 4.1.5 on 2023-03-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_info_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='product_desc',
            field=models.TextField(),
        ),
    ]
